### ISSUE TITLE
Error when creating new wallet

### ISSUE THREAD

**Issue by ffracer** [neo-project/neo-gui#139] opened 2018-01-08 19:05 UTC
Please help. Updated to the latest GUI ver 2.5.2

When opening existing wallet or creating a new wallet, it gives a message about the wallet file that will be converted. After selecting "Yes" an error message "Unhandled exception has occurred in your application"

Please see details of message below. Think my PC might be missing a component,, as I tested on another PC and it works fine. 

_See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box._

**Comment by erikzhang** [comment] 2018-01-09 01:11
Duplicate of #118

**Closed as completed by erikzhang** 2018-01-09 01:11 UTC
Labels: duplicate
