### ISSUE TITLE
Upgrade to 2.6 cant load new format

### ISSUE THREAD

**Issue by scombo** [neo-project/neo-gui#206] opened 2018-03-07 11:44 UTC
Hi All 
Upgraded to 2.6 - wallet is fully synced. When opening the wallet I am prompted to update the wallet file to the newer version. If I accept the upgrade I get the following message 

Unhandled exception has occurred and gives me the option to Get details or Continue or quit .

Any suggestions would be much appreciated

**Comment by erikzhang** [comment] 2018-03-07 11:57
Duplicate of #118

**Comment by jrsikors** [comment] 2018-03-07 16:45
The resolution in #118 is:
To solve this, please install vs2010 redist x86 and x64:
https://www.microsoft.com/de-de/download/details.aspx?id=14632
https://www.microsoft.com/de-de/download/details.aspx?id=5555

**Comment by scombo** [comment] 2018-03-10 00:52
Many thanks - made the changes and wallet updated  until yesterday when it stopped at block 2000190 and has not moved since then

**Comment by scombo** [comment] 2018-03-10 00:53
Many thanks - made the changes and wallet updated until yesterday when it stopped at block 2000190 and has not moved since then

**Comment by jrsikors** [comment] 2018-03-10 15:29
Close out and re-open (if you haven't already).  You should have 3 numbers..
first number = your wallet sync level
second number = your computer sync level
third number = the latest block in chain

Ideally you want to NOT open your wallet until the 2nd and 3rd numbers are sync'd up.. THEN open your wallet and the first number will go up fast

**Comment by scombo** [comment] 2018-03-11 04:35
Thanks jsikors. - I have tried restarting the wallet but the issue seems to be that no blocks are being processed. The 2nd and 3rd numbers have stayed at block 2000190 for a couple of days now despite  the wallet showing 10 connections

**Comment by jrsikors** [comment] 2018-03-11 16:43
I don't call myself an expert on this matter -- but if I were in your shoes, I would try these things in this order (though I can't decide if I would do 1 or 2 first, either would be fine, i don't think 1 is going to do anything anyways but it's worth a shot)

1st:
close NEO-GUI, delete peers.dat, re-start NEO-GUI, leave it running for an hour and see if there's any change

2nd:
open neo-gui, try going to wallet -> rebuild index

3rd .. most painful and last resort:
close NEO-GUI, rename CHAIN folder to CHAIN-OLD , and re-start NEO-GUI.  
Unfortunately this will start the sync again... but should fix you up

**Comment by jrsikors** [comment] 2018-03-12 18:55
it's actually interesting that you stated block 2000190... a guy just posted #211  ... different issue, but he was also getting stuck on EXACTLY block 2000190 ... but he said he was on version 2.5.. which is an older version of NEO-GUI.

So perhaps you aren't really running version 2.6... you should triple check that.

**Comment by scombo** [comment] 2018-03-12 22:09
Thanks for the update - but as far as I can tell I am on the latest version 2.6.6596.21976(Neo gui Help window). Have tried step 1 and busy with 2 although wallet (1st) number is updating the 2nd and 3rd are still on block 2000190

**Comment by jrsikors** [comment] 2018-03-12 22:51
I would stop trying to open your wallet file while you are trying to figure this out.  Your issues are with the 2nd and 3rd numbers and loading your wallet file just adds another unnecessary variable.

Don't worry about opening your wallet file until your 2nd and 3rd numbers are good to go.

**Comment by jrsikors** [comment] 2018-03-12 22:51
saw this as well:
https://www.reddit.com/r/NEO/comments/83j7dl/is_your_neo_node_stuck_at_2000190/

I would try that before you try my 3rd idea

**Comment by scombo** [comment] 2018-03-14 02:50
Hi jsikors - many thanks for the advice so far however I have now downloaded and unzipped chain from the link above which all seemed to work, however now the wallet won't even start. If I click on the neo-gui icon it "thinks" for a while and then just stops. Nothing further happens have tried running as admin as well with the same result

**Comment by jrsikors** [comment] 2018-03-14 03:19
Check and temporarily disable antivirus... but my guess is the NEO-GUI doesn’t like what it sees in the chain folder.  You can try renaming it to chain-old and see if that’s the culprit

**Comment by scombo** [comment] 2018-03-14 03:47
Yup wallet started immediately!

**Comment by scombo** [comment] 2018-03-14 03:49
Would you suggest downloading zip again from somewhere else?

**Comment by scombo** [comment] 2018-03-14 04:03
Removed chain directory and unzipped from Chain09Mar.zip again with same result. Now trying to download chain zip file again

**Comment by jrsikors** [comment] 2018-03-14 04:22
If you are doing that zip.. maybe try getting rid of the chain.acc.zip .. I wouldn’t do both

Sorry.  Such a pain!

**Comment by jrsikors** [comment] 2018-03-14 19:33
I haven't tried the CoZ chain yet personally.  I did it the hard way and just spent a few days syncing from 0/0/0 with no chain.acc.zip or CoZ bootstrap.  If you do it this way -- I would suggest closing down NEO-GUI every 8-12 hours if possible.  NEO-GUI starts eating a lot of CPU resources while syncing.

Basically the only place to check for a new / different one is:
https://github.com/CityOfZion/awesome-neo
scroll down a little bit or page search for "Blockchain Bootstrap" .. it will take you to
Blockchain Bootstrap Files For C# Client
MainNet
MainNet (S3 - Chain09Mar.zip) - Up to block 2002315.

Your problem is weird .. because the chain.acc.zip works as designed -- but you are getting stuck on block 2000190 , which is a different problem.

At this stage this is what I would do if I were in your position ...
Option A -- Try Again)
Step 1)  Delete *ALL* contents of chain folder, everything in there
Step 2)  Delete peers.dat
Step 3)  Download the Chain09Mar.zip from https://s3.eu-west-2.amazonaws.com/ashant-neo/Chain09Mar.zip
Step 4)  Unzip Chain09Mar.zip into your Chain folder
Step 5)  Remove the chain.acc.zip from your NEO-GUI "root" directory.  Sin, since you are using a bootstrap, i dont think you want this
Step 6)  Start NEO-GUI
Step 7)  Give it a while -- it might take 30-45 minutes to start ... unless you are looking at task manager and see NEO-GUI.exe is NOT running and has crashed.  If it crashed you could always go look at Event Viewer and see if there's some kind of error --and paste that here.

Option B -- Wait a little bit and use a different wallet like NEON in the meantime until the "2000190 block" problem gets resolved

It sucks, but I'm positive you would be golden with the chain.acc.zip (preferred method) if it wasn't for the new "2000190 block problem"

Just bad luck/timing, sorry man !

**Comment by scombo** [comment] 2018-03-15 01:27
Hi js - followed the above steps and it crashed immediately again - got this message in the errorlog though

Neo.IO.Data.LevelDB.LevelDBException
Corruption: corrupted compressed block contents
   at Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.IO.Data.LevelDB.Iterator.CheckError()
   at Neo.IO.Data.LevelDB.Iterator.Key()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Program.Main()


So I am going to try downloading the zip file again and try again

**Comment by jrsikors** [comment] 2018-03-15 19:48
It actually looks like CoZ removed the https://s3.eu-west-2.amazonaws.com/ashant-neo/Chain09Mar.zip bootstrap ... judging on some of these  comments ... i wonder if it wasn't fixing problems and causing more problems.

Might explain why it wasn't working for you.

That being said -- I think your only hope is to go the chain.acc.zip route, AKA the "official" way.

**Comment by jrsikors** [comment] 2018-03-18 17:23
Other thoughts ...
If you are stuck on a block, try closing down NEO-GUI ... delete peers.dat ... re-open neo-gui

**Comment by scombo** [comment] 2018-03-19 23:09
Hi Js 

Firstly,  thanks for sticking with this - I have been trying to do a full resync for the past few days - just waiting for it to update which is extremely slow - has been running for days now. Have to say its been my worst experience with any wallet so far. Will keep you updated if I ever get there

**Comment by jrsikors** [comment] 2018-03-21 17:43
I posted this in a couple other issues -- I decided to jump in the ocean with you all and give it a shot ... this is what I did and I was sync'd within 24 hours.  If your 2nd number or 3rd number is stuck -- consider nuking it and start over..

follow these instructions to the T.. don't cheat or think you know better or think I typo'd something .. I didn't :smile: 

So I just did this
step 1) Downloaded the latest https://github.com/neo-project/neo-gui/releases/latest
step 2) Downloaded the chain.acc.zip from http://static.neo.org/client/chain.acc.zip ... do not unzip do not unzip
Step 3) Unzipped the neo client from step 1 to c:\NEO26 (a fresh directory where you've never had NEO installed)
Step 4) COPIED DIDNT UNZIP the chain.acc.zip from step 2 to the FRESH directory you created in step 3
Step 5) Launched neo-gui.exe from the FRESH directory you created in step 3

Within 10 minutes of opening ... my 2nd and 3rd numbers are already at 1.25 million each ... and i have 0 'connections' ... which means the chain.acc.zip is doing its job.

after about an hour, it looks like it stopped 'speed syncing' at around 0 / 1.8 million / 1.8 million ... and the remaining 200,000 blocks blocks will need to sync normally .. which will probably be a while.

After 24 hours I was sync'd up.

I have not opened my wallet file yet -- nor will I until I am sync'd

So -- I think you need to pay very close attention to my steps and do them exactly. You aren't doing something right... either you are:
A) Not on the latest 2.6 NEO GUI, my step 1 will cover that
B) Have a bad chain.acc.zip, my step 2 should cover that
C) Have data in your chain folder already which is preventing the chain.acc.zip from working properly.. my step 3 will cover that (will create a brand new fresh directory for Chain folder)
D) Are unzipping the chain.acc.zip ... my step 3 will cover that

**Comment by scombo** [comment] 2018-03-29 00:28
Hi Js

Well after following steps above , I have restarted and been running it for a few days but the second number is going up very slowly . 3rd number is 2078560 (which it got too quickly) 2nd is only 1491600 

Assuming that this is just a situation where I just have to sit and wait for it

**Comment by jrsikors** [comment] 2018-04-02 16:55
What's the status on this one -- you good to go now @scombo  ?  Sorry for late response !

**Comment by scombo** [comment] 2018-04-06 02:55
Hi Jeff

Still waiting for the 2nd and third numbers to update, its getting there but unbelivably slowly. Just going to sit it out now until I can try and open the wallet and then I will take my balance out and try another wallet

Thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jrsikors** [comment] 2018-04-06 03:00
You can open your wallet at any time and grab the private key(s).. shouldn’t need to wait for full sync.

**Closed as completed** 2018-05-29 07:42 UTC
Labels: duplicate
