### ISSUE TITLE
neo-gui beug

### ISSUE THREAD

**Issue by alexandreravelli** [neo-project/neo-gui#73] opened 2017-09-28 11:54 UTC
Hello,

Today I have loaded my Neo Gui wallet, latest version - 2.3

And now i can't open my neo-gui now. (i use windows 10 - 64bit)

The error log : 

Neo.Implementations.Blockchains.LevelDB.LevelDBException
Corruption: not an sstable (bad magic number)
   à Neo.Implementations.Blockchains.LevelDB.NativeHelper.CheckError(IntPtr error)
   à Neo.Implementations.Blockchains.LevelDB.DB.Get(ReadOptions options, Slice key)
   à Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   à Neo.Program.Main()

Could you help me ?

Thanks

**Comment by erikzhang** [comment] 2017-10-09 08:19
Duplicate of #69

**Closed as completed** 2017-12-13 03:20 UTC
Labels: duplicate, help wanted
