### ISSUE TITLE
Transfer neo from Account not working

### ISSUE THREAD

**Issue by Kiqui** [neo-project/neo-gui#151] opened 2018-01-14 22:06 UTC
Hi , 
I am trying to withdraw Neo from my account . But it says that Transaction initiated but signiture is incomplete. Any help apreciated.

**Comment by Yippyiyo** [comment] 2018-01-15 00:36
See #150

**Comment by jrsikors** [comment] 2018-01-19 19:39
I see you have another issue open ... is this issue resolved?  Is this the same/related to your other issue?

**Comment by Kiqui** [comment] 2018-01-20 01:32
Yes I thought the two might be connected. The issue is not resolved.

**Comment by jrsikors** [comment] 2018-01-27 16:38
@erikzhang  you can close this one and make it a duplicate of #152

**Comment by erikzhang** [comment] 2018-01-28 03:37
Duplicate of #152

**Closed as completed by erikzhang** 2018-01-28 03:37 UTC
Labels: help wanted
