### ISSUE TITLE
Transfer from NEO-Gui automatically separate two addresses

### ISSUE THREAD

**Issue by ziplock94** [neo-project/neo-gui#175] opened 2018-01-31 08:33 UTC
Hi.
I have made transfer from NEO-Gui to Bittrex, however when I checked transaction, it generates 2 transactions in one time. half portion went to Bittrex, and another half  went to unknown address.
So now I do not have any access to this address, is it possible to access that unknown created address?

Thank you.

**Comment by jrsikors** [comment] 2018-01-31 15:54
1)  Please provide the TX number and/or address(es).. can't really assist much without this information

2)  Let's say you had 20 NEO...
       Did you transfer 20 NEO to bittrex account and it split 10 / 10?
      or Did you transfer 10 of your 20 NEO, and 10 went to Bittrex, and the other 10 went somewhere else?

**Comment by jrsikors** [comment] 2018-01-31 17:11
might be related /similar to #165

**Comment by ziplock94** [comment] 2018-02-01 02:13
Dear Jeff

Hi. This is Tats.
Yes. Exactly same issue!

And this transaction is my friend asked me to find out the way to 
get back.

So is it better to transfer this email to my friend?
Only he has private key for from address.

Thank you.

Regards
Tats


----- Original Message -----

**Comment by jrsikors** [comment] 2018-02-01 02:23
What is the transaction number/string ?

https://neotracker.io/

**Comment by ziplock94** [comment] 2018-02-01 03:12
this transaction


https://neotracker.io/tx/d832459fcbf9c1838d4ccc173cda4bc92a34efa992c5269cc30b31155b438b7b
>
>
>
>


----- Original Message -----

**Comment by jrsikors** [comment] 2018-02-01 03:38
So an exact duplicate of #165 

Yeah I don't have any further insight than what I said in #165  , sorry .. hopefully someone else might.

**Comment by jrsikors** [comment] 2018-02-03 15:56
@erikzhang close this as duplicate and reference #165  please

**Comment by erikzhang** [comment] 2018-02-04 06:36
Duplicate of #165

**Closed as completed by erikzhang** 2018-02-04 06:36 UTC
Labels: help wanted
