### ISSUE TITLE
Neo Gui 2.5.2 stop at block 1766193/1766193/1766193

### ISSUE THREAD

**Issue by Shinryuu0** [neo-project/neo-gui#130] opened 2018-01-02 21:51 UTC
Hello. I created a new wallet and downloaded the block with the client. It stops at the above block and doesn't move on. I'm still connected to 44 nodes.
Neo Tracker and my NEON wallet say the actual block is 1771403 right now when I write this.

What can I do to get synced with the Neo Gui?

**Comment by aspeg** [comment] 2018-01-03 01:18
I've been stuck on same block for a few days now as well

**Comment by xellos53** [comment] 2018-01-03 11:41
Hello. I created a new wallet and downloaded the block with the client. It stops at the above block and doesn't move on. 
Neo Tracker and my NEON wallet say the actual block is 1771403 right now when I write this.

What can I do to get synced with the Neo Gui?

1.use old  wallet rpx wallet also same 2.3.6474 ver
2new wallet .Neo Gui 2.5.2 stop at block 1766193/1766193/1766193

left the sync about 4 hours..but nothing change..please help master...

**Comment by erikzhang** [comment] 2018-01-04 12:42
Duplicate of #117

**Closed as completed by erikzhang** 2018-01-04 12:42 UTC
Labels: help wanted

**Comment by caizhiyuanrise** [comment] 2018-01-14 05:11
Best to stop the Neo-Gui and restart. I do not know why it is that way, but a lot of time when the Neo-Gui starts at the beginning, it does not get all blocks in one run. Several new startings and it works at one point. Maybe some protection build in...

**Comment by xellos53** [comment] 2018-01-14 10:24
Orite..I already download new again..seem its ok now..tq brother for tips..
Neo to the moon !!!

**Comment by caizhiyuanrise** [comment] 2018-01-14 18:05
Also restarting Windows art the same time helps. It is then fastest getting connections to clients and getting the numbers up on par with the block-hight
