### ISSUE TITLE
neo-gui  编译失败 提示 CX509PrivateKey 不存在AlgorithmName 属性/('CX509PrivateKey' does not contain a definition for 'AlgorithmName' )

### ISSUE THREAD

**Issue by danielzy301** [neo-project/neo-gui#127] opened 2018-01-02 06:43 UTC
'CX509PrivateKey' does not contain a definition for 'AlgorithmName'

**Comment by erikzhang** [comment] 2018-01-02 07:49
Duplicate of #97

**Closed as completed by erikzhang** 2018-01-02 07:49 UTC
Labels: duplicate, wontfix
