### ISSUE TITLE
Please Help !! Cant open my Neo Gui Wallet V 2.5.2

### ISSUE THREAD

**Issue by flip93** [neo-project/neo-gui#131] opened 2018-01-03 16:23 UTC
![neo gui problem](https://user-images.githubusercontent.com/35072887/34528840-6fee6404-f0aa-11e7-9160-9b1dd6f6348b.png)

Everything was fine today. Suddenly i cant open it anymore. This is the second time. I allready uninstalled and install new version and load the blocks new. 
And I un and installed net framework new... 

CLR20r3??? Dont know what this is.

**Comment by jrsikors** [comment] 2018-01-07 22:06
Did you check out:
https://github.com/neo-project/neo-gui/issues/116

Another issue I had with the 2.5.2 was anti-virus kept trying to quarantine the neo-gui.exe

**Comment by jrsikors** [comment] 2018-01-07 23:17
Having a similar issue as well.  Was using a DB3 as wallet file on 2.5.0 just fine the other day.  Things were good on 2.5.0 .. I tried swapping to 2.5.2. When it asked me to upgrade my wallet .. the client crashed.  I swapped back to 2.5.0 and restored an older copy of my db3 file , and even on the older .db3 file i'm getting the pop-up asking about using a wallet on an older version. 

Loaded up an earlier copy ... it's currently re-syncing.  If this works -- I might just create a new wallet file on 2.5.2 and send my coins there.. or go to neon wallet either temporarily or permanently. 

Or revert back to 2.3.5 with an older copy of wallet file. 

Pretty scary stuff !

**Comment by jrsikors** [comment] 2018-01-08 01:21
opened up 2.5.2
waited until i had at least 1 connection
wallet -> Open Wallet Database -> my db3 file
Migrate Wallet pop up:
  Opening wallet files in older versions, update to newest format?
 Note:  updated files cannot be openned by clients in older versions!
I click "No"
starts to resync the first # after Height from 0.  So it started from 0/1791532/1791532
new folder called  "Index_########" is created with a ldb files, current, lock, log, manifest-0000002
eventually my balance for NEO and NeoGas, and transactions, start showing up

~~~~~~~~~~

Next Test 


opened up 2.5.2
waited until i had at least 1 connection
wallet -> Open Wallet Database -> my db3 file
Migrate Wallet pop up:
  Opening wallet files in older versions, update to newest format?
 Note:  updated files cannot be openned by clients in older versions!
I click "Yes"

Neo-gui:
  Unhandled exception has occurred in your application.  If you click Continue, the application will ignore this error and attempt to continue.  If you click Quit, the Application will close immediately.

Exception has been thrown by the target of an invocation.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Replicon.Cryptography.SCrypt.MMA, Version=1.1.6.13, Culture=neutral, PublicKeyToken=4e0c787cc79e77b2' or one of its dependencies. The specified module could not be found. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Replicon.Cryptography.SCrypt.MMA.dll' or one of its dependencies. The specified module could not be found.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.<EnsureCrtInitialized>b__3()
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.<>c__DisplayClass8`1.<EscapeExecutionContext>b__5()
   --- End of inner exception stack trace ---
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.EscapeExecutionContext[T](Func`1 callback)
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.EnsureCrtInitialized()
   at Replicon.Cryptography.SCrypt.MixedModeAssemblyKeyDerivationFunction.DeriveKey(Byte[] password, Byte[] salt, UInt64 N, UInt32 r, UInt32 p, UInt32 derivedKeyLengthBytes)
   at Neo.Wallets.KeyPair.Export(String passphrase)
   at Neo.Implementations.Wallets.NEP6.NEP6Wallet.CreateAccount(Contract contract, KeyPair key)
   at Neo.Implementations.Wallets.NEP6.NEP6Wallet.Migrate(String path, String db3path, String password)
   at Neo.UI.MainForm.打开钱包数据库OToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
neo-gui
    Assembly Version: 2.5.6557.29435
    Win32 Version: 2.5.6557.29435
    CodeBase: file:///c:/myfolder/clients/neo252/neo-gui.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Neo
    Assembly Version: 2.5.2.0
    Win32 Version: 2.5.2.0
    CodeBase: file:///c:/myfolder/clients/neo252/Neo.DLL
----------------------------------------
Neo.VM
    Assembly Version: 2.0.4.0
    Win32 Version: 2.0.4.0
    CodeBase: file:///c:/myfolder/clients/neo252/Neo.VM.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Configuration.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Configuration.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Configuration.Json.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.FileProviders.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Configuration.FileExtensions.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.FileProviders.Physical.DLL
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Primitives.DLL
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.FileSystemGlobbing.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.1.20720
    CodeBase: file:///c:/myfolder/clients/neo252/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.25908.02
    CodeBase: file:///c:/myfolder/clients/neo252/System.IO.Compression.DLL
----------------------------------------
Microsoft.AspNetCore.Http.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Http.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Hosting.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Hosting.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.DependencyInjection.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Server.Kestrel.DLL
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Configuration.EnvironmentVariables.DLL
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.25908.02
    CodeBase: file:///c:/myfolder/clients/neo252/System.Net.Sockets.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.DependencyInjection.DLL
----------------------------------------
Microsoft.AspNetCore.Http.Features
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Http.Features.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.2.1
    Win32 Version: 4.6.25519.03
    CodeBase: file:///c:/myfolder/clients/neo252/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
Microsoft.AspNetCore.Http
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Http.DLL
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Options.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Logging.DLL
----------------------------------------
Microsoft.Extensions.ObjectPool
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.ObjectPool.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Core
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Server.Kestrel.Core.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting.Server.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.Hosting.Server.Abstractions.DLL
----------------------------------------
Microsoft.Net.Http.Headers
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Net.Http.Headers.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.3.0
    Win32 Version: 
    CodeBase: file:///c:/myfolder/clients/neo252/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///c:/myfolder/clients/neo252/System.Runtime.DLL
----------------------------------------
Microsoft.AspNetCore.WebSockets
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.AspNetCore.WebSockets.DLL
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Hosting.Abstractions.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.EntityFrameworkCore
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.EntityFrameworkCore.DLL
----------------------------------------
System.Interactive.Async
    Assembly Version: 3.0.3000.0
    Win32 Version: 3.1.1.0
    CodeBase: file:///c:/myfolder/clients/neo252/System.Interactive.Async.DLL
----------------------------------------
Remotion.Linq
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.1.30000
    CodeBase: file:///c:/myfolder/clients/neo252/Remotion.Linq.DLL
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Caching.Memory.DLL
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Extensions.Caching.Abstractions.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.Data.Sqlite
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.Data.Sqlite.DLL
----------------------------------------
Microsoft.EntityFrameworkCore.Sqlite
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.EntityFrameworkCore.Sqlite.DLL
----------------------------------------
Microsoft.EntityFrameworkCore.Relational
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.17205
    CodeBase: file:///c:/myfolder/clients/neo252/Microsoft.EntityFrameworkCore.Relational.DLL
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///c:/myfolder/clients/neo252/System.ComponentModel.Annotations.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.2.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///c:/myfolder/clients/neo252/System.Collections.Immutable.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
SQLitePCLRaw.batteries_v2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///c:/myfolder/clients/neo252/SQLitePCLRaw.batteries_v2.DLL
----------------------------------------
SQLitePCLRaw.provider.e_sqlite3
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///c:/myfolder/clients/neo252/SQLitePCLRaw.provider.e_sqlite3.DLL
----------------------------------------
SQLitePCLRaw.core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///c:/myfolder/clients/neo252/SQLitePCLRaw.core.DLL
----------------------------------------
Replicon.Cryptography.SCrypt
    Assembly Version: 1.1.6.13
    Win32 Version: 1.1.6.13
    CodeBase: file:///c:/myfolder/clients/neo252/Replicon.Cryptography.SCrypt.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by jrsikors** [comment] 2018-01-08 01:31
Also -- I'm unable to even create a new .json wallet file.  If I go to Wallets -> Create new wallet -> give it a name and password ... I get the exact same errors as above.
  
Windows 10 Pro
version 1709
build 16299.192

**Comment by flip93** [comment] 2018-01-08 07:46
Thank you Sir for your messages. Yeah thats very scary stuff :( 
My plan is to resync my wallet ... when i do that i can open it.. but allways when i close the wallet i get this error ... then i wait until i can see my balance again and transfer it to a exchange to keep it safe for a second... and then i change to neon wallet. Its more simple i gues. Maybe my bitdefender antivirus program makes this problem. I try to check this

**Comment by erikzhang** [comment] 2018-01-08 08:11
Duplicate of #118

**Closed as completed by erikzhang** 2018-01-08 08:11 UTC
Labels: duplicate, help wanted

**Comment by jrsikors** [comment] 2018-01-08 17:07
Thanks Erik -- confirmed the solution in #118 fixed my issue.  I am now able to generate a new wallet.  I already moved my stuff to NEON.. but will move back soon once sync'd!
